spring:
  application:
    name: voucher
server:
  port: 8081
eureka:
  instance:
    ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8083/eureka
      
ribbon:
  http:
    client:
      enabled: true