spring:
  application:
    name: purchase
  datasource:
    url: jdbc:postgresql://eureka-server:5432/purchase
    username: postgres
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8082
  
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8083/eureka