spring:
  application:
    name: purchase
  datasource:
    url: jdbc:postgresql://postgresql:5432/purchase
    username: postgres
    password: fiap
  jpa:
    hibernate:
      ddl-auto: update
  liquibase.change-log: classpath:/database/master-changelog.xml  
  
server:
  port: 8082
  
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8083/eureka
