server:
  port: 8080
 
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
      - id: voucher
        uri: lb://VOUCHER
        predicates:
        - Path=/voucher/**
        filters:
        - RewritePath=/voucher(?<path>/?.*), $\{path}
      - id: purchase
        uri: lb://PURCHASE
        predicates:
        - Path=/purchase/**
        filters:
        - RewritePath=/purchase(?<path>/?.*), $\{path}
        
ribbon:
  http:
    client:
      enabled: true
    

    
